### PR TITLE
[enh] Level 7

### PR DESCRIPTION
**Pull request by zamentur**
I have done some change to improve this package:

* fix nginx traversal issue
* add a message to the admin
* fix bad rm -rf $
* use common helpers
* check source integrity
* do checksum to detect change from user on configuration
...
-

### CODE REVIEW

**Comment by alexAubin** [comment]
Bump ? :s

**Comment by alexAubin** [comment]
Bumpzor ... the app is now flagged as unmaintained so we should discuss wether to merge this or not with the @YunoHost-Apps/apps-group team ?

**Comment by ldidry** [comment]
Please, do that: I'm not aware of the last YNH devs (such as templates for conf files), would be better to discuss with well-informed people.

**Comment by maniackcrudelis** [comment]
Had a quick look, agree on the principle of merging, especially with the agreement of @ldidry.

But strongly disagree with the modifications made on this app by this PR...
Too many useless functions in _common and usage of jinja2 (which is obviously only for the core, etc...)

**Pull request merged**
