### PR TITLE
change back to 7.3.3

### PR DESCRIPTION
**Pull request by MadMan247**
## Problem

App was broken. It was updated to 7.3.3 by salamander, and then a bot's automatic update request to 7.2.0 was merged. This brings it back to 7.3.3. see issue #22 

## Solution
I undid what the bot did, and changed the app version to 7.3.3 instead of 2.8.1~ynh5 to prevent future issues.

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

It should be good to merge, but please be sure to test. I will test myself to double check after submitting this pull request.

### CODE REVIEW

**Comment by MadMan247** [comment]
yep, just installed this branch, worked like a charm
image
please test and merge soon!

**Comment by MadMan247** [comment]
@Salamandar please merge 🥺 🙏

**Comment by MadMan247** [comment]
Could someone please merge this? I promise it is not wrought with malware. I promise it brings SVG edit to a better state than it currently is.

**Comment by MadMan247** [comment]
please review and merge? @ericgaspar ? @Salamandar ?

**Comment by ericgaspar** [comment]
!testme

**Review by ericgaspar — APPROVED** [review]

**Comment by ericgaspar** [comment]
thanks for your work!

**Pull request merged**
